### ISSUE TITLE
Crash with jewelry mod

### ISSUE THREAD

**Issue by VaporeonScripts** [ZsoltMolnarrr/Jewelry#19]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'jewelry' at 'net.jewelry.JewelryMod'!
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at MC//net.minecraft.client.MinecraftClient.redirect$ide000$notenoughcrashes$catchFabricInit(MinecraftClient.java:33672)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.jewelry.JewelryMod
	at java.base@21.0.4/java.lang.Class.forName0(Native Method)
	at java.base@21.0.4/java.lang.Class.forName(Class.java:534)
	at java.base@21.0.4/java.lang.Class.forName(Class.java:513)
	at app//net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 11 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: net/fabric_extras/structure_pool/api/StructurePoolConfig [in thread "Render thread"]
	at net.jewelry.config.Default.<clinit>(Default.java:15)
	at net.jewelry.JewelryMod.<clinit>(JewelryMod.java:22)
	at java.base@21.0.4/java.lang.Class.forName0(Native Method)
	at java.base@21.0.4/java.lang.Class.forName(Class.java:534)
	at java.base@21.0.4/java.lang.Class.forName(Class.java:513)
	at app//net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at com.supermartijn642.core.registry.RegistryEntryAcceptor$Handler.gatherAnnotatedFields(RegistryEntryAcceptor.java:71)
	at com.supermartijn642.core.CoreLib.beforeInitialize(CoreLib.java:79)
	at MC//net.minecraft.client.MinecraftClient.handler$len000$supermartijn642corelib$beforeInit(MinecraftClient.java:43671)
	... 8 more

**Comment by VaporeonScripts** [comment]
forgot to say, latest version 1.21.1 fabric,latest fabric loader,arch linux distro system, prism launcher

**Comment by ZsoltMolnarrr** [comment]
Install Structure Pool API mod.
Next update will contain correct Fabric dependency declaration.
